import JSZip from 'jszip';
import type { ExportFile, ExportMetadata } from '../midi/types';

export async function createExportZip(
  files: ExportFile[],
  metadata: ExportMetadata
): Promise<Blob> {
  const zip = new JSZip();

  // Add MIDI files
  files.forEach(file => {
    zip.file(file.filename, file.data);
  });

  // Add metadata JSON
  zip.file('metadata.json', JSON.stringify(metadata, null, 2));

  // Add README
  const readme = generateReadme(metadata);
  zip.file('README.txt', readme);

  return await zip.generateAsync({ type: 'blob' });
}

function generateReadme(metadata: ExportMetadata): string {
  return `MC-101 MIDI Splitter - Export Package
Generated: ${metadata.generatedAt}
Source File: ${metadata.sourceFile}

OVERVIEW
========
This package contains MIDI files prepared for import into your Roland MC-101.
Each file represents a clip ready to be loaded into tracks A, B, C, or D.

FILES INCLUDED
==============
${metadata.files.map(f => {
  const splitInfo = f.splitIndex !== undefined ? ` (Part ${f.splitIndex})` : '';
  return `${f.filename}${splitInfo}
  Track: ${f.trackId}
  Steps: ${f.stepRange.start} - ${f.stepRange.end}
  Source Tracks: ${f.sourceTracks.join(', ')}`;
}).join('\n\n')}

IMPORT INSTRUCTIONS
===================
1. Copy the .mid files to your MC-101's SD card in the MUSIC folder
2. On the MC-101, press [SHIFT] + [TRACK SELECT] to enter CLIP mode
3. Select the target track (A, B, C, or D)
4. Press [SHIFT] + [VALUE] to open the file browser
5. Navigate to your MIDI file and press [ENTER] to import
6. Repeat for each track

NOTES
=====
- Maximum 128 steps per clip (automatically split if longer)
- Tempo and time signature preserved from source
- Program changes ${metadata.stripProgramChange ? 'removed' : 'included'}
- Unsupported MIDI events filtered out

For more information about using MIDI with MC-101, refer to the official
Roland MC-101 Owner's Manual.

SETTINGS USED
=============
PPQ: ${metadata.ppq}
Steps per Bar: ${metadata.splitSettings.stepsPerBar}
Max Steps per Clip: ${metadata.splitSettings.maxStepsPerClip}

---
Generated by MC-101 MIDI Splitter
`;
}
