import JSZip from 'jszip';
import type { ExportFile, ExportMetadata } from '../midi/types';

export async function createExportZip(
  files: ExportFile[],
  metadata: ExportMetadata
): Promise<Blob> {
  const zip = new JSZip();

  // Add MIDI files
  files.forEach(file => {
    zip.file(file.filename, file.data);
  });

  // Add metadata JSON
  zip.file('metadata.json', JSON.stringify(metadata, null, 2));

  // Add README
  const readme = generateReadme(metadata);
  zip.file('README.txt', readme);

  return await zip.generateAsync({ type: 'blob' });
}

function generateReadme(metadata: ExportMetadata): string {
  return `MIDI Splitter - Export Package
Generated: ${metadata.generatedAt}
Source File: ${metadata.sourceFile}

OVERVIEW
========
This package contains MIDI files split and prepared for import into your
hardware synth or DAW. Each file represents a clip or track segment.

FILES INCLUDED
==============
${metadata.files.map(f => {
  const splitInfo = f.splitIndex !== undefined ? ` (Part ${f.splitIndex})` : '';
  return `${f.filename}${splitInfo}
  Track: ${f.trackId}
  Steps: ${f.stepRange.start} - ${f.stepRange.end}
  Source Tracks: ${f.sourceTracks.join(', ')}`;
}).join('\n\n')}

IMPORT INSTRUCTIONS
===================
For Hardware Synths:
1. Transfer all .mid files to your device via USB or SD card
2. Navigate to your device's MIDI import function
3. Select and import each .mid file to the corresponding track
4. Load consecutive clips in sequence for longer patterns

For DAWs:
1. Drag and drop .mid files directly into your project
2. Each file represents a track or clip segment
3. Align clips sequentially based on the step ranges above

NOTES
=====
- Files automatically split at ${metadata.splitSettings.maxStepsPerClip} steps
- Tempo and time signature preserved from source
- Program changes ${metadata.stripProgramChange ? 'removed' : 'included'}
- Standard MIDI Format Type 1 (single-track)

SETTINGS USED
=============
PPQ: ${metadata.ppq}
Steps per Bar: ${metadata.splitSettings.stepsPerBar}
Max Steps per Clip: ${metadata.splitSettings.maxStepsPerClip}

---
Generated by MIDI Splitter
`;
}
